---
- name: Create gluster cluster
  hosts: gluster_servers
  remote_user: root
  gather_facts: false

  vars:
    gluster_cluster_hosts:
      - 10.70.41.212
      - 10.70.42.156
    gluster_cluster_volume: testvol
    gluster_cluster_replica_count: 2
    gluster_cluster_force: "yes"
    gluster_cluster_transport: "tcp"
    gluster_cluster_bricks: "10.70.41.212:/mnt/brick1/b1 10.70.42.156:/mnt/brick2/b2"

  roles:
    - gluster.cluster
